---
label: Services
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
pages:
- content/services/_index.md/service-one.md
